# 网站地址
baseURL: "http://www.pullock.fun"
# 语言
#nlanguageCode: "zh-cn"
# 默认的内容语言
defaultContentLanguage: "zh-cn"
languages:
  zh-cn:
    languageCode: "zh-cn"
# 自动检测是否包含中文/日文/韩文，该参数会影响摘要和字数统计功能，建议设置为true
hasCJKLanguage: true
# 若为 false，`Getting Started` 这样的英文标签将会被转换为 `getting-started`
preserveTaxonomyNames: true
title: "Pullock"
# 设置使用的主题名称 (默认储存在 /themes/THEMENAME/)
theme: "smol"
# 分页 
paginate: 10
paginatePath: "page"
buildFuture: true
# 启用 Emoji
enableEmoji: true
# 创建robots.txt，建议设置为true
enableRobotsTXT: true
# URL路径区分大小写
DisablePathToLower: true
# 定义文章访问路径
permalinks: 
  posts: /:year/:month/:day/:title

params: 
  subtitle: "脚踏实地"

menu: 
  main: 
  - url: /posts/
    identifier: posts
    name: Posts
    weight: 1
  - url: /categories
    identifier: categories
    name: Categories
    weight: 2
  - url: /tags
    identifier: tags
    name: Tags
    weight: 3
  footer: 
  - name: Hugo
    url: https://gohugo.io/
    weight: 1
  - name: Smol
    url: https://github.com/colorchestra/smol
    weight: 2
  - name: Github
    url: https://github.com/pulllock
    weight: 3
copyright: Pullock.fun
